/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoADatos.AdministradorData;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import entidades.Administrador;
import java.awt.Menu;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author recre
 */
public class Login extends javax.swing.JFrame {

     AdministradorData admData = new AdministradorData();
         
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTexUsuario1 = new javax.swing.JTextField();
        jPass1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButRegistro1 = new javax.swing.JButton();
        jButCancelar1 = new javax.swing.JButton();
        jButIniciar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 500));

        Fondo.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setText("¿No tienes cuenta?");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        jButRegistro1.setText("Registrate");
        jButRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegistro1ActionPerformed(evt);
            }
        });

        jButCancelar1.setText("Cancelar");
        jButCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelar1ActionPerformed(evt);
            }
        });

        jButIniciar1.setText("Iniciar Sesión");
        jButIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButIniciar1ActionPerformed(evt);
            }
        });

        Fondo.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jTexUsuario1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jPass1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jButRegistro1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jButCancelar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Fondo.setLayer(jButIniciar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexUsuario1)
                            .addComponent(jPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButIniciar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(jButRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTexUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButIniciar1)
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButRegistro1)
                    .addComponent(jButCancelar1))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegistro1ActionPerformed
        // Creamos una nueva instancia de la jInternalFrame de registro del administrador
    Registro registroAdminFrame = new Registro();
    
    // Agregamos la ventana interna al escritorio (JDesktopPane Fondo) del jFrame principal
    Fondo.add(registroAdminFrame);
    
    // Mostrar la ventana interna
    registroAdminFrame.setVisible(true);
       
    }//GEN-LAST:event_jButRegistro1ActionPerformed

    private void jButIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButIniciar1ActionPerformed
        String usuario = jTexUsuario1.getText();
        String pass = new String(jPass1.getPassword());

    // Realizar la validación de las credenciales en la base de datos utilizando el método inicioSesion
    Administrador admin = admData.inicioSesion(usuario, pass);

    if (admin != null) {
        // Las credenciales son válidas, permite el acceso al menú
        Main menu = new Main();
        menu.setVisible(true);
        this.dispose(); // Cierra el formulario de inicio de sesión
    } else {
        // Las credenciales no son válidas, muestra un mensaje de error
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Inténtalo de nuevo.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
    }
   
    }//GEN-LAST:event_jButIniciar1ActionPerformed

    private void jButCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelar1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatArcOrangeIJTheme.setup();
//        FlatDarkFlatIJTheme.setup();
        FlatArcDarkOrangeIJTheme.setup();
        UIManager.getFont("h2");
//        UIManager.put( "Component.focusWidth" , 3 );
        UIManager.put( "ScrollBar.showButtons" , true );
//         UIManager.put( "Button.arc", 300 );

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Fondo;
    private javax.swing.JButton jButCancelar1;
    private javax.swing.JButton jButIniciar1;
    private javax.swing.JButton jButRegistro1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPass1;
    private javax.swing.JTextField jTexUsuario1;
    // End of variables declaration//GEN-END:variables
}
