/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;
import com.formdev.flatlaf.ui.FlatUIUtils;
import entidades.Libro;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author asdasd
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMBuscarLibros = new javax.swing.JMenuItem();
        jMAgregarlibro = new javax.swing.JMenuItem();
        jMModificarLib = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMNuevoSocio = new javax.swing.JMenuItem();
        jMListaSocio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jNuevoPrestamo = new javax.swing.JMenuItem();
        jMmodificarPrestamo = new javax.swing.JMenuItem();
        jMDevolución = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        jMPrestamosPorSocio = new javax.swing.JMenuItem();
        JMPrestamosVencidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        jMenu1.setText("Libros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMBuscarLibros.setText("Buscar Libros");
        jMBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBuscarLibrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMBuscarLibros);

        jMAgregarlibro.setText("Agregar Nuevo Libro");
        jMAgregarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAgregarlibroActionPerformed(evt);
            }
        });
        jMenu1.add(jMAgregarlibro);

        jMModificarLib.setText("Modificar Libro");
        jMModificarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMModificarLibActionPerformed(evt);
            }
        });
        jMenu1.add(jMModificarLib);

        jMenuBar1.add(jMenu1);

        jMenuSocios.setText("Socios");

        jMNuevoSocio.setText("Nuevo Socio");
        jMNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNuevoSocioActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMNuevoSocio);

        jMListaSocio.setText("Lista de Socios Activos");
        jMListaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaSocioActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMListaSocio);

        jMenuBar1.add(jMenuSocios);

        jMenu2.setText("Prestamos");

        jNuevoPrestamo.setText("Nuevo Prestamo");
        jNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNuevoPrestamoActionPerformed(evt);
            }
        });
        jMenu2.add(jNuevoPrestamo);

        jMmodificarPrestamo.setText("Modificar Prestamo");
        jMmodificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmodificarPrestamoActionPerformed(evt);
            }
        });
        jMenu2.add(jMmodificarPrestamo);

        jMDevolución.setText("Devolución");
        jMDevolución.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDevoluciónActionPerformed(evt);
            }
        });
        jMenu2.add(jMDevolución);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Devoluciones");

        jMenuItem2.setText("Cancelar Devolución");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        JMConsultas.setText("Consultas");

        jMPrestamosPorSocio.setText("Prestamos por Socio");
        JMConsultas.add(jMPrestamosPorSocio);

        JMPrestamosVencidos.setText("Prestamos Vencidos");
        JMPrestamosVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPrestamosVencidosActionPerformed(evt);
            }
        });
        JMConsultas.add(JMPrestamosVencidos);

        jMenuBar1.add(JMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
//bugeado

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBuscarLibrosActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       VistaListaLibros listarLibros = new VistaListaLibros();
       listarLibros.setVisible(true);
       Escritorio.add(listarLibros);
       Escritorio.moveToFront(listarLibros);

    }//GEN-LAST:event_jMBuscarLibrosActionPerformed

    private void jMAgregarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAgregarlibroActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       Vista_NuevoLibro nuevo = new Vista_NuevoLibro();
       nuevo.setVisible(true);
       Escritorio.add(nuevo);
       Escritorio.moveToFront(nuevo);
        
    }//GEN-LAST:event_jMAgregarlibroActionPerformed

    private void jNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNuevoPrestamoActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       VistaPrestamoNuevo Vista_li = new VistaPrestamoNuevo();
       Vista_li.setVisible(true);
       Escritorio.add(Vista_li);
       Escritorio.moveToFront(Vista_li);      
       
    }//GEN-LAST:event_jNuevoPrestamoActionPerformed

    private void jMNuevoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNuevoSocioActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       VistaSocios socios = new VistaSocios ();
       socios.setVisible(true);
       Escritorio.add(socios);
       Escritorio.moveToFront(socios);
    }//GEN-LAST:event_jMNuevoSocioActionPerformed

    private void jMDevoluciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDevoluciónActionPerformed
        Escritorio.removeAll();
       Escritorio.repaint();
       VistaDevolucion devolver = new VistaDevolucion();
       devolver.setVisible(true);
       Escritorio.add(devolver);
       Escritorio.moveToFront(devolver);
    }//GEN-LAST:event_jMDevoluciónActionPerformed

    private void jMListaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaSocioActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       VistaListaSocios listaSocios = new VistaListaSocios();
       listaSocios.setVisible(true);
       Escritorio.add(listaSocios);
       Escritorio.moveToFront(listaSocios);
    }//GEN-LAST:event_jMListaSocioActionPerformed

    private void JMPrestamosVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPrestamosVencidosActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       VistaPrestamosVencidos prestVencidos = new VistaPrestamosVencidos();
       prestVencidos.setVisible(true);
       Escritorio.add(prestVencidos);
       Escritorio.moveToFront(prestVencidos);
    }//GEN-LAST:event_JMPrestamosVencidosActionPerformed

    private void jMModificarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMModificarLibActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       Vista_ModificarLibro modifLibro = new Vista_ModificarLibro();
       modifLibro.setVisible(true);
       Escritorio.add(modifLibro);
       Escritorio.moveToFront(modifLibro);
    }//GEN-LAST:event_jMModificarLibActionPerformed

    private void jMmodificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmodificarPrestamoActionPerformed
        Escritorio.removeAll();
       Escritorio.repaint();
       Vista_ModificarPrestamo modifPrestamo = new Vista_ModificarPrestamo();
       modifPrestamo.setVisible(true);
       Escritorio.add(modifPrestamo);
       Escritorio.moveToFront(modifPrestamo);
    }//GEN-LAST:event_jMmodificarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        FlatArcOrangeIJTheme.setup();
//        FlatDarkFlatIJTheme.setup();
        FlatArcDarkOrangeIJTheme.setup();
        UIManager.getFont("h2");
//        UIManager.put( "Component.focusWidth" , 3 );
        UIManager.put( "ScrollBar.showButtons" , true );
//         UIManager.put( "Button.arc", 300 );


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenuItem JMPrestamosVencidos;
    private javax.swing.JMenuItem jMAgregarlibro;
    private javax.swing.JMenuItem jMBuscarLibros;
    private javax.swing.JMenuItem jMDevolución;
    private javax.swing.JMenuItem jMListaSocio;
    private javax.swing.JMenuItem jMModificarLib;
    private javax.swing.JMenuItem jMNuevoSocio;
    private javax.swing.JMenuItem jMPrestamosPorSocio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuSocios;
    private javax.swing.JMenuItem jMmodificarPrestamo;
    private javax.swing.JMenuItem jNuevoPrestamo;
    // End of variables declaration//GEN-END:variables
}
