/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoADatos.AdministradorData;
import entidades.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author recre
 */
public class Registro extends javax.swing.JInternalFrame {

    AdministradorData admData = new AdministradorData();
    
    public Registro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoReg = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTexUsuarioReg = new javax.swing.JTextField();
        jPassReg = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButReg = new javax.swing.JButton();

        FondoReg.setBackground(new java.awt.Color(255, 153, 0));
        FondoReg.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO!!!");

        jLabel2.setText("Ingrese un Usuario y una Constraseña");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        jButReg.setText("Registrarse");
        jButReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegActionPerformed(evt);
            }
        });

        FondoReg.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jTexUsuarioReg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jPassReg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoReg.setLayer(jButReg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout FondoRegLayout = new javax.swing.GroupLayout(FondoReg);
        FondoReg.setLayout(FondoRegLayout);
        FondoRegLayout.setHorizontalGroup(
            FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoRegLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(FondoRegLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addGroup(FondoRegLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addGroup(FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassReg)
                            .addComponent(jTexUsuarioReg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButReg, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoRegLayout.setVerticalGroup(
            FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoRegLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexUsuarioReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(FondoRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jPassReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButReg)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegActionPerformed
        try {
            String usuario = jTexUsuarioReg.getText(); 
            String pass = new String(jPassReg.getPassword());
            
            if (usuario.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios ");
                                
            } else {
                Administrador admNuevo = new Administrador(usuario, pass);
                admData.registrarAdmin(admNuevo);
                //jtId.setText(libroNuevo.getIdLibro() + "");                
            JOptionPane.showMessageDialog(this, "Se ha registrado correctamente");   
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un código en un formato válido ");
        }  
         this.dispose();
    }//GEN-LAST:event_jButRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane FondoReg;
    private javax.swing.JButton jButReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassReg;
    private javax.swing.JTextField jTexUsuarioReg;
    // End of variables declaration//GEN-END:variables
}
