/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import entidades.Ejemplar;
import entidades.Libro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asdasd
 */
public class Vista_ejemplar extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Vista_ejemplar
     */
    public Vista_ejemplar() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // buscar por nombre
        jTable1.getComponentAt(1, 1);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(evt.getComponent().getClass());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        modelo.addColumn("Codigo Ejemplar");

        modelo.addColumn("Codigo Libro");

        modelo.addColumn("Stock");

        modelo.addColumn("Estado");
        jTable1.setModel(modelo);

// cargar ejemplares
        Libro lib_ = new Libro(1, 1, "hola_titulo", "autor", "genero", "editorial", true);
        //Ejemplares(lib_);
        ArrayList<Libro> libro_array = new ArrayList<>(3);

        libro_array.add(0, lib_);
        Libro lib_1 = new Libro(2, 2, "hola_titulo_2", "autor_2", "genero_2", "editorial_2", true);
        libro_array.add(1, lib_1);
        Libro lib_2 = new Libro(3, 3, "hola_titulo_3", "autor_3", "genero_3", "editorial_3", true);
        libro_array.add(2, lib_2);

        ArrayList<Ejemplar> ejemp = new ArrayList<>(3);
        Ejemplar ejmpla = new Ejemplar(1, libro_array.get(0), 1, true);
        Ejemplar ejmpla_1 = new Ejemplar(2, libro_array.get(1), 12, true);
        Ejemplar ejmpla_2 = new Ejemplar(3, libro_array.get(2), 15, true);

        ejemp.add(0, ejmpla);
        ejemp.add(1, ejmpla_1);
        ejemp.add(2, ejmpla_2);

        System.out.println(lib_);
        for (Ejemplar e : ejemp) {

            modelo.addRow(new Object[]{e.getIdEjemplar(), e.getLibro().getTitulo(), e.getStock(), e.isActivo()});

        }

    }

//private void Ejemplares(Libro libro){
//Ejemplar eje = new Ejemplar(1,libro,10,true);
////modelo.addRow(new Object[] {eje.getIdEjemplar(),eje.getLibro().getTitulo(),eje.getStock(),eje.isActivo()} );
////ejempl(libro);
//}
//public List<Ejemplar> ejempl(Libro libro) {
//    System.out.println("");
//   // ArrayList<Ejemplar> ejemplares = new ArrayList<>();
//   
//    
//    //modelo.addRow(new Object[] {eje.getIdEjemplar(),eje.getLibro().getTitulo(),eje.getStock(),eje.isActivo()} );
//    
////    for (int i = 0; i < 10; i++) {
////        
////        Ejemplar eje = new Ejemplar(i,libro,10,true);
////   
////        
////    ejemplares.add(eje);
////     ejemplares.get(i);
////    System.out.println(ejemplares.get(i));
////    }
//    
////    System.out.println(ejemplares);
//   return ejemplares;
//}
}
