/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoADatos.LectorData;
import entidades.Lector;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author recre
 */
public class VistaListaSocios extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    Lector lecAct = null;

    /**
     * Creates new form VistaListaSocios
     */
    public VistaListaSocios() {
        initComponents();
        armarCabecera();
        // Habilitar la selección de filas
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLSocios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBMostrar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();

        jLSocios.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLSocios.setText(" LISTA DE SOCIOS");

        jTable1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jBMostrar.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jBMostrar.setText("Mostrar");
        jBMostrar.setPreferredSize(new java.awt.Dimension(100, 40));
        jBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.setPreferredSize(new java.awt.Dimension(100, 40));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.setPreferredSize(new java.awt.Dimension(100, 40));
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBLimpiar.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setPreferredSize(new java.awt.Dimension(100, 40));
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jLSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarActionPerformed

        if (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        //Usamos este metodo para eliminar todas las filas existentes para cargar nuevos datos.
        }

        // Creamos una instancia de LectorData
        LectorData lecData = new LectorData(); 
        // List<Lector> listaLectores = lecData.listarLectores(); // Obtiene la lista de lectores
        //  Lector lector = new Lector();

        for (Lector lector : lecData.listarLectores()) {
            cargarLista(lector); // Agrega cada lector a la tabla

        }
    }//GEN-LAST:event_jBMostrarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para modificar.");
            return;
        }

        // Habilitamos la edición en la celda de cada columna
        jTable1.editCellAt(filaSeleccionada, 1);
        jTable1.editCellAt(filaSeleccionada, 2);
        jTable1.editCellAt(filaSeleccionada, 3);
        jTable1.editCellAt(filaSeleccionada, 4);
        jTable1.editCellAt(filaSeleccionada, 5);
        jTable1.editCellAt(filaSeleccionada, 6);

        // Coloca el foco en la celda para permitir la edición
        jTable1.getEditorComponent().requestFocus();

        // Obtenemos el ID del lector seleccionado en la tabla (asumiendo que está en la primera columna)
        int idLector = (int) jTable1.getValueAt(filaSeleccionada, 0);

        // Buscamos el lector en la base de datos utilizando su ID
        LectorData lecData = new LectorData();
        Lector lectorSeleccionado = lecData.buscarLectorPorId(idLector);

        // Obtenemos los datos editados de la fila seleccionada
        String nuevoApellido = (String) jTable1.getValueAt(filaSeleccionada, 1);
        String nuevoNombre = (String) jTable1.getValueAt(filaSeleccionada, 2);
        String nuevoDni = (String) jTable1.getValueAt(filaSeleccionada, 3);
        String nuevoDireccion = (String) jTable1.getValueAt(filaSeleccionada, 4);
        String nuevoTelefono = (String) jTable1.getValueAt(filaSeleccionada, 5);
        String nuevoMail = (String) jTable1.getValueAt(filaSeleccionada, 6);

        // Actualizamos los datos en el objeto Lector
        lectorSeleccionado.setApellido(nuevoApellido);
        lectorSeleccionado.setNombre(nuevoNombre);
        lectorSeleccionado.setDni(Integer.parseInt(nuevoDni));
        lectorSeleccionado.setDireccion(nuevoDireccion);
        lectorSeleccionado.setTelefono(Integer.parseInt(nuevoTelefono));
        lectorSeleccionado.setMail(nuevoMail);

        // Actualizamos el lector en la base de datos
        lecData.modificarLector(lectorSeleccionado);

        // Refrescamos la tabla para mostrar los cambios en la interfaz
        modelo.setValueAt(nuevoApellido, filaSeleccionada, 1);
        modelo.setValueAt(nuevoNombre, filaSeleccionada, 2);
        modelo.setValueAt(nuevoTelefono, filaSeleccionada,3);
        modelo.setValueAt(nuevoDireccion, filaSeleccionada, 4);
        modelo.setValueAt(nuevoMail, filaSeleccionada, 6);

    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        // Esto limpia todas las filas de la tabla
    }//GEN-LAST:event_jBLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBMostrar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLSocios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("IdLector");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");
        modelo.addColumn("E-Mail");
        modelo.addColumn("Estado");
        jTable1.setModel(modelo);
    }

    private void cargarLista(Lector lector) {
        modelo.addRow(new Object[]{lector.getIdLector(), lector.getApellido(), lector.getNombre(), lector.getDni(), lector.getDireccion(), lector.getTelefono(), lector.getMail(), lector.isActivo()});
    }

}
